services:
  response-generator:
    build: ..
    ports:
      - "8001:8001"

  cache-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - response-generator
    environment:
      - VERSION=v2

  traffic-generator:
    build: ../Generador_Trafico
    depends_on:
      - cache-service
    environment:
      - VERSION=v2
      - MODE=uniform